packages:
  - ".sandcastle"
overrides:
  nanoid: "3.3.8"
  semver: "7.7.2"
allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  msgpackr-extract: true
  netlify-cli: true
  sharp: true
  unix-dgram: true
minimumReleaseAge: 1440
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1
  - chokidar@4.0.3
  - "@netlify/edge-bundler@14.10.3"
  - "@netlify/zip-it-and-ship-it@14.7.1"
  - "@netlify/serverless-functions-api@2.16.0"
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.1
  vite-plus: 0.2.1
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
