allowBuilds:
  esbuild: true
  msgpackr-extract: false
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.1
  vite-plus: 0.2.1
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
