name: CD

run-name: CD — ${{ github.event.workflow_run.head_branch == 'master' && 'staging' || 'production' }} · ${{ github.event.workflow_run.head_commit.message }}

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

concurrency:
  group: cd-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'master'
    environment: github-pages
    permissions:
      id-token: write
      pages: write
    steps:
      - uses: actions/download-artifact@v8
        continue-on-error: true
        with:
          name: dist-staging
          path: dist
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - uses: actions/upload-pages-artifact@v5
        with:
          path: dist
      - id: deployment
        uses: actions/deploy-pages@v5

  deploy-prod:
    if: github.event.workflow_run.conclusion == 'success' && startsWith(github.event.workflow_run.head_branch, 'v')
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version-file: .node-version
      - run: vp i --frozen-lockfile
      - uses: actions/download-artifact@v8
        continue-on-error: true
        with:
          name: dist-prod
          path: dist
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - run: vpx convex deploy
        env:
          CONVEX_DEPLOY_KEY: ${{ secrets.CONVEX_DEPLOY_KEY }}
      - run: vpx netlify deploy --dir=./dist --prod --no-build
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
